# 안전벨
setwd("C:/Users/Heejuu/Downloads")
library("dplyr")
gangnam <- read.csv("서울특별시_강남구_안전비상벨위치.csv")
gangnam <- gangnam%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
gangdong <- read.csv("서울특별시_강동구_안전비상벨위치.csv")
gangdong <- gangdong%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
gangbuk <- read.csv("서울특별시_강북구_안전비상벨위치.csv")
gangbuk <- gangbuk%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
gangseo <- read.csv("서울특별시_강서구_안전비상벨위치.csv")
gangseo <- gangseo%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
gwanak <- read.csv("서울특별시_관악구_안전비상벨위치.csv")
gwanak <- gwanak%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
gwangjin <- read.csv("서울특별시_광진구_안전비상벨위치.csv")
gwangjin <- gwangjin%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
guro <- read.csv("서울특별시_구로구_안전비상벨위치.csv")
guro <- guro%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
geumcheon <- read.csv("서울특별시_금천구_안전비상벨위치.csv")
geumcheon <- geumcheon%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
nowon <- read.csv("서울특별시_노원구_안전비상벨위치.csv")
nowon <- nowon%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
dobong <- read.csv("서울특별시_도봉구_안전비상벨위치.csv")
dobong <- dobong%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
ddm <- read.csv("서울특별시_동대문구_안전비상벨위치.csv")
ddm <- ddm%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
dongjak <- read.csv("서울특별시_동작구_안전비상벨위치.csv")
dongjak <- dongjak%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
mapo <- read.csv("서울특별시_마포구_안전비상벨위치.csv")
mapo <- mapo%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
sdm <- read.csv("서울특별시_서대문구_안전비상벨위치.csv")
sdm <- sdm%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
seocho <- read.csv("서울특별시_서초구_안전비상벨위치.csv")
seocho <- seocho%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
sd <- read.csv("서울특별시_성동구_안전비상벨위치.csv")
sd <- sd%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
sb <- read.csv("서울특별시_성북구_안전비상벨위치.csv")
sb <- sb%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
songpa <- read.csv("서울특별시_송파구_안전비상벨위치.csv")
songpa <- songpa%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
yangcheon <- read.csv("서울특별시_양천구_안전비상벨위치.csv")
yangcheon <- yangcheon%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
ydp <- read.csv("서울특별시_영등포구_안전비상벨위치.csv")
ydp <- ydp%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
yongsan <- read.csv("서울특별시_용산구_안전비상벨위치.csv")
yongsan <- yongsan%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
yp <- read.csv("서울특별시_은평구_안전비상벨위치.csv")
yp <- yp%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
jongno <- read.csv("서울특별시_종로구_안전비상벨위치.csv")
jongno <- jongno%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
jung <- read.csv("서울특별시_중구_안전비상벨위치.csv")
jung <- jung%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)
jungnang <- read.csv("서울특별시_중랑구_안전비상벨위치.csv")
jungnang <- jungnang%>%select(안전비상벨관리번호, 설치위치, 소재지도로명주소, 소재지지번주소, 위도, 경도, 관리기관명, 관리기관전화번호)

seoul_bell = rbind(ddm, dobong, dongjak, gangbuk, gangdong, gangnam, gangseo, geumcheon, guro, gwanak, gwangjin, jongno, jung, jungnang, mapo, nowon, sb,sd,sdm,seocho,songpa,yangcheon,ydp,yongsan, yp)


# 일반음식점
gangnam_r <- read.csv("서울시 강남구 일반음식점 식품위생업소 현황.csv")
gangnam_r <- gangnam_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
gangdong_r <- read.csv("서울시 강동구 일반음식점 식품위생업소 현황.csv")
gangdong_r <- gangdong_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
gangbuk_r <- read.csv("서울시 강북구 일반음식점 식품위생업소 현황.csv")
gangbuk_r <- gangbuk_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
gangseo_r<- read.csv("서울시 강서구 일반음식점 식품위생업소 현황.csv")
gangseo_r<- gangseo_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
gwanak_r<- read.csv("서울시 관악구 일반음식점 식품위생업소 현황.csv")
gwanak_r<- gwanak_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
gwangjin_r <- read.csv("서울시 광진구 일반음식점 식품위생업소 현황.csv")
gwangjin_r<- gwangjin_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
guro_r<- read.csv("서울시 구로구 일반음식점 식품위생업소 현황.csv")
guro_r<- guro_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
geumcheon_r<- read.csv("서울시 금천구 일반음식점 식품위생업소 현황.csv")
geumcheon_r<- geumcheon_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
nowon_r<- read.csv("서울시 노원구 일반음식점 식품위생업소 현황.csv")
nowon_r <- nowon_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
dobong_r<- read.csv("서울시 도봉구 일반음식점 식품위생업소 현황.csv")
dobong_r<- dobong_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
ddm_r<- read.csv("서울시 동대문구 일반음식점 식품위생업소 현황.csv")
ddm_r<- ddm_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
dongjak_r<- read.csv("서울시 동작구 일반음식점 식품위생업소 현황.csv")
dongjak_r<- dongjak_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
mapo_r<- read.csv("서울시 마포구 일반음식점 식품위생업소 현황.csv")
mapo_r<- mapo_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
sdm_r<- read.csv("서울시 서대문구 일반음식점 식품위생업소 현황.csv")
sdm_r<- sdm_r%>%filter(폐업일자=="")%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
seocho_r<- read.csv("서울시 서초구 일반음식점 식품위생업소 현황.csv")
seocho_r<- seocho_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
sd_r <- read.csv("서울시 성동구 일반음식점 식품위생업소 현황.csv")
sd_r <- sd_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
sb_r<- read.csv("서울시 성북구 일반음식점 식품위생업소 현황.csv")
sb_r<- sb_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
songpa_r<- read.csv("서울시 송파구 일반음식점 식품위생업소 현황.csv")
songpa_r<- songpa_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
yangcheon_r<- read.csv("서울시 양천구 일반음식점 식품위생업소 현황.csv")
yangcheon_r<- yangcheon_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
ydp_r <- read.csv("서울시 영등포구 일반음식점 식품위생업소 현황.csv")
ydp_r <- ydp_r %>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
yongsan_r<- read.csv("서울시 용산구 일반음식점 식품위생업소 현황.csv")
yongsan_r<- yongsan_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
yp_r <- read.csv("서울시 은평구 일반음식점 식품위생업소 현황.csv")
yp_r <- yp_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
jongno_r <- read.csv("서울시 종로구 일반음식점 식품위생업소 현황.csv")
jongno_r<- jongno_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
jung_r<- read.csv("서울시 중구 일반음식점 식품위생업소 현황.csv")
jung_r<- jung_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
jungnang_r<- read.csv("서울시 중랑구 일반음식점 식품위생업소 현황.csv")
jungnang_r<- jungnang_r%>%filter(is.na(폐업일자))%>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명)
j2 = jungnang_r[!duplicated(jungnang_r[,c('업소일련번호','소재지지번','행정동명')]),]

seoul_r = rbind(ddm_r, dobong_r, dongjak_r, gangbuk_r,gangdong_r, gangnam_r, gangseo_r, geumcheon_r, guro_r, gwanak_r, gwangjin_r, jongno_r, jung_r, jungnang_r, mapo_r, nowon_r, sb_r,sd_r,sdm_r,seocho_r,songpa_r,yangcheon_r,ydp_r,yongsan_r, yp_r)
write.csv(seoul_r,file="seoul_r.csv", row.names=FALSE)

r1 = read.csv("seoul_r.csv")
r5 <- r1[1:40000, ]
write.csv(r5, file="r5.csv", row.names = FALSE)
r6 <- r1[40001:80000, ]
write.csv(r6, file="r6.csv", row.names = FALSE)
r7 <- r1[80001:100000, ]
write.csv(r7, file="r7.csv", row.names = FALSE)
r8 <- r1[100001:120000, ]
write.csv(r8, file="r8.csv", row.names = FALSE)
r9 <- r1[120001:200000, ]
write.csv(r9, file="r9.csv", row.names = FALSE)
r10 <- r1[200001:223475, ]
write.csv(r10, file="r10.csv", row.names = FALSE)

# duplicate
r5_shp <- read.csv("r5.shp.csv")
r5_shp = r5_shp[!duplicated(r5_shp[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r5_shp, file="r5.shp.csv", row.names = FALSE)
r5_shp_e <- read.csv("r5.shp.err.csv")
r5_shp_e = r5_shp_e[!duplicated(r5_shp_e[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r5_shp_e, file="r5.shp.err.csv", row.names = FALSE)
r6_shp <- read.csv("r6.shp.csv")
r6_shp = r6_shp[!duplicated(r6_shp[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r6_shp, file="r6.shp.csv", row.names = FALSE)
r6_shp_e <- read.csv("r6.shp.err.csv")
r6_shp_e = r6_shp_e[!duplicated(r6_shp_e[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r6_shp_e, file="r6.shp.err.csv", row.names = FALSE)
r7_shp <- read.csv("r7.shp.csv")
r7_shp = r7_shp[!duplicated(r7_shp[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r7_shp, file="r7.shp.csv", row.names = FALSE)
r7_shp_e <- read.csv("r7.shp.err.csv")
r7_shp_e = r7_shp_e[!duplicated(r7_shp_e[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r7_shp_e, file="r7.shp.err.csv", row.names = FALSE)
r8_shp <- read.csv("r8.shp.csv")
r8_shp = r8_shp[!duplicated(r8_shp[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r8_shp, file="r8.shp.csv", row.names = FALSE)
r8_shp_e <- read.csv("r8.shp.err.csv")
r8_shp_e = r8_shp_e[!duplicated(r8_shp_e[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r8_shp_e, file="r8.shp.err.csv", row.names = FALSE)
r9_shp <- read.csv("r9.shp.csv")
r9_shp = r9_shp[!duplicated(r9_shp[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r9_shp, file="r9.shp.csv", row.names = FALSE)
r9_shp_e <- read.csv("r9.shp.err.csv")
r9_shp_e = r9_shp_e[!duplicated(r9_shp_e[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r9_shp_e, file="r9.shp.err.csv", row.names = FALSE)
r10_shp <- read.csv("r10.shp.csv")
r10_shp = r10_shp[!duplicated(r10_shp[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r10_shp, file="r10shp.csv", row.names = FALSE)
r10_shp_e <- read.csv("r10.shp.err.csv")
r10_shp_e = r10_shp_e[!duplicated(r10_shp_e[,c('업소일련번호','소재지지번','행정동명')]),]
write.csv(r10_shp_e, file="r10.shp.err.csv", row.names = FALSE)

# 음식점 다 합치기
d1 <- read.csv("r5.shp.csv")
d2 <- read.csv("r6.shp.csv")
d3 <- read.csv("r7.shp.csv")
d4 <- read.csv("r8.shp.csv")
d5 <- read.csv("r9.shp.csv")
d6 <- read.csv("r10.shp.csv")
d7 <- read.csv("r10_1.shp.csv")
d8<- read.csv("r5_1.shp.csv")
d9 <- read.csv("r6_1.shp.csv")
d10 <- read.csv("r7_1.shp.csv")
d11 <- read.csv("r8_1.shp.csv")
d12 <- read.csv("r9_1.shp.csv")
d13 <- read.csv("r10_1.shp.csv")
d1 <- d1 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d2 <- d2 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d3 <- d3 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d4 <- d4 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d5 <- d5 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d6 <- d6 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d7 <- d7 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d8 <- d8 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d9 <- d9 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d10 <- d10 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d11 <- d11 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d12 <- d12 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)
d13 <- d13 %>% select(업소일련번호, 업소명, 소재지도로명, 소재지지번, 행정동명, 위도, 경도)


seoul_restaurant <- rbind(d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13)
write.csv(seoul_restaurant, file="seoul_restaurant.csv", row.names = FALSE)
